### ISSUE TITLE
Ajouter une Homepage

### ISSUE THREAD

**Issue by camfrelat** [AdrienEtienne/coconut_island_app#2]
Création de la  #homepage :

1. Système de bulles (icones ronds avec dessins à l'intérieur) pour accéder aux différentes options.
2. Une option menu en haut à gauche pour l'aspect legal de l'app et aussi un onglet aide (peut avoir d'autre
s options dans le futur)
3. En bas à droite une possibilité d'avoir un onglet profil pour pourvoir accéder à sa page de login (MP), informations personnelles et aussi pourquoi pas liste de courses ou légumes et recettes mises en favoris. 
4. Design épuré et simple, le mois actuel est écrit dans un décors de saison (des flocons pour l'hiver, des feuilles pour l'automne etc...)

> [](url)
[première page mock idée .pdf](https://github.com/AdrienEtienne/coconut_island_app/files/6109534/premiere.page.mock.idee.pdf)

**Comment by AdrienEtienne** [comment]
Tu en penses quoi de la premiere page comme ca pour le moment?


https://user-images.githubusercontent.com/2983803/111161068-97828480-85ff-11eb-9d37-38873230e730.mov

**Comment by AdrienEtienne** [comment]
@camfrelat si tu trouves ca pas mal, on peut avoir ça intégré et continuer avec la prochaine fonctionnalité que tu aimerais voir implémentée :)

**Comment by camfrelat** [comment]
J'aime bien franchement. Le seul truc c'est que je suis pas sure qu'on comprenne tout de suite qu'on cherche des légumes. Peut être il manque un truc au dessus ? Après quand on y réfléchis les gens savent quelle app ils ont téléchargé... t'en penses quoi toi ?

**Comment by AdrienEtienne** [comment]
Tu as raison, on peut ajouter un texte plus parlant. Tu as suggéré "Legumes et Fruits de saison" il me semble?

Si tu peux me donner le texte a ajouter et la position (par rapport au mois) ca serait cool. Comme ca je peux te montrer un fois changé

**Comment by AdrienEtienne** [comment]
Tu en penses quoi de just ce texte pour le moment @camfrelat ?

<img width="456" alt="Screenshot 2021-03-22 at 07 33 34" src="https://user-images.githubusercontent.com/2983803/111949462-a5775e80-8b45-11eb-92b0-4bb016b9f962.png">

**Comment by camfrelat** [comment]
ouais c 'est bien je trouve :)
