### ISSUE TITLE
Lister les legumes pour le mois

### ISSUE THREAD

**Issue by AdrienEtienne** [AdrienEtienne/coconut_island_app#5]
* Nouvelle page ou les legumes sont listés

**Comment by AdrienEtienne** [comment]
@camfrelat tu en penses quoi?


https://user-images.githubusercontent.com/2983803/113051441-74142800-9202-11eb-9492-4d4c4f2fb865.mov

**Comment by camfrelat** [comment]
c'est super top pour le moment, je vais essayer de reclasser les légumes par mois pour pouvoir les ranger rapidement.

**Comment by AdrienEtienne** [comment]
Ok @camfrelat j'integre et ferme cette issue car je considere comme terminé. Je vais essayer de rapidement faire la page mock up pour les veggies pour que tu me dises ce que tu en penses
